Payment\DataAccessBundle\Entity\AccountType:
    type: entity
    table: account_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 128
            fixed: false
            nullable: false
        description:
            type: string
            length: 256
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: false
            column: is_active
    lifecycleCallbacks: {  }
