Payment\DataAccessBundle\Entity\Consumption:
    type: entity
    repositoryClass: Payment\DataAccessBundle\Entity\ConsumptionRepository
    table: consumption
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        costId:
            type: integer
            unsigned: false
            nullable: false
            column: cost_id
        accountId:
            type: integer
            unsigned: false
            nullable: false
            column: account_id
        costValue:
            type: decimal
            nullable: false
            column: cost_value
        readDate:
            type: datetime
            nullable: false
            column: read_date
        systemDate:
            type: datetime
            nullable: false
            column: system_date
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
    lifecycleCallbacks: {  }
