Payment\DataAccessBundle\Entity\Fines:
    type: entity
    table: fines
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        cost:
            type: decimal
            nullable: false
        fineDate:
            type: datetime
            nullable: false
            column: fine_date
    manyToOne:
        finesType:
            targetEntity: FinesType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fines_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        member:
            targetEntity: Member
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                member_id:
                    referencedColumnName: id
            orphanRemoval: false
        systemUser:
            targetEntity: SystemUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
