Payment\DataAccessBundle\Entity\ManagerialMember:
    type: entity
    repositoryClass: Payment\DataAccessBundle\Entity\ManagerialMemberRepository
    table: managerial_member
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        managerialId:
            type: integer
            unsigned: false
            nullable: false
            column: managerial_id
        chargeId:
            type: integer
            unsigned: false
            nullable: false
            column: charge_id
        memberId:
            type: integer
            unsigned: false
            nullable: false
            column: member_id
        activationDate:
            type: datetime
            nullable: false
            column: activation_date
        desactivationDate:
            type: datetime
            nullable: true
            column: desactivation_date
        isActive:
            type: boolean
            nullable: false
            column: is_active
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
    lifecycleCallbacks: {  }
