Payment\DataAccessBundle\Entity\PaymentTypeType:
    type: entity
    table: payment_type_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 128
            fixed: false
            nullable: false
        description:
            type: string
            length: 512
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
