Payment\DataAccessBundle\Entity\PaymentType:
    type: entity
    repositoryClass: Payment\DataAccessBundle\Entity\PaymentTypeRepository
    table: payment_type
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 64
            fixed: false
            nullable: false
        description:
            type: string
            length: 512
            fixed: false
            nullable: false
        cost:
            type: decimal
            nullable: false
        isActive:
            type: boolean
            nullable: false
            column: is_active
    manyToOne:
        paymentTypeType:
            targetEntity: PaymentTypeType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                payment_type_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
