Payment\DataAccessBundle\Entity\Transaction:
    type: entity
    repositoryClass: Payment\DataAccessBundle\Entity\TransactionRepository
    table: transaction
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        totalValue:
            type: decimal
            nullable: false
            column: total_value
        systemDate:
            type: datetime
            nullable: false
            column: system_date
    manyToOne:
        managerial:
            targetEntity: Managerial
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                managerial_id:
                    referencedColumnName: id
            orphanRemoval: false
        systemUser:
            targetEntity: SystemUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_user_id:
                    referencedColumnName: id
            orphanRemoval: false
        transactionType:
            targetEntity: TransactionType
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                transaction_type_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
