<?php

namespace Payment\DataAccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends EntityRepository
{
	public function findIncomeByAccount($paymentId)
	{
		$queryBuilder = $this->getEntityManager()->createQueryBuilder('i');
		$queryBuilder->add('select', 'i');
		$queryBuilder->add('from', 'PaymentDataAccessBundle:Income i');
		$queryBuilder->andWhere('i.payment = ?1');
		$queryBuilder->setParameter(1, $paymentId);
		$query = $queryBuilder->getQuery();
		$result = $query->getResult();
		return $result;
	}
}