<?php

namespace Payment\DataAccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NavigationItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationItemRepository extends EntityRepository
{
	
	/**
	 * Función que devuelve todos los items para el menú
	 *
	 * @param int $level  Nivel del Menú
	 * @param int $parentId Identificador del Padre del Menú
	 * @param string $sc security
	 *
	 */
	public function getMenus($parentId, $rol)
	{
		$rol = '%'.$rol.'%';
		$queryBuilder = $this->getEntityManager()->createQueryBuilder('n');
		$queryBuilder->add('select', 'n');
		$queryBuilder->orderBy('n.ordering');
		$queryBuilder->add('from', 'PaymentDataAccessBundle:NavigationItem n');
		$queryBuilder->andWhere($queryBuilder->expr()->eq('n.isActive', '1'));
		$queryBuilder->andWhere($queryBuilder->expr()->orX(
				$queryBuilder->expr()->like('n.roles', '?2'),
				$queryBuilder->expr()->like('n.roles', '?3')
				));
		
		$queryBuilder->setParameter(2, $rol);
		$queryBuilder->setParameter(3, '%ROLE_USER%');		
		
		$query = $queryBuilder->getQuery();
		$result = $query->getResult();
		return $result;
	}	
}