<?php

namespace Payment\DataAccessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
	public function findPaymentTypeByNameToList($finesTypeText, $offset, $limit, $count = true)
	{
	
		$queryBuilder = $this->getEntityManager()->createQueryBuilder('ft');
		if ($count) {
			$queryBuilder->add('select', $queryBuilder->expr()->count('ft.id'));
		} else {
			$queryBuilder->add('select', 'ft');
			$queryBuilder->orderBy('ft.name');
			$queryBuilder->setFirstResult($offset);
			$queryBuilder->setMaxResults($limit);
		}
		$queryBuilder->add('from', 'PaymentDataAccessBundle:PaymentType ft');
			
		if ($finesTypeText != null) {
			$finesTypeText = str_replace(' ', '%', $finesTypeText);
			$finesTypeText = '%' . strtolower($finesTypeText) . '%';
			$queryBuilder->andWhere(
					$queryBuilder->expr()->like($queryBuilder->expr()->lower('ft.name'), '?1')
			);
			$queryBuilder->setParameter(1, $finesTypeText);
	
		}
		$query = $queryBuilder->getQuery();
		$result = $query->getResult();
		return $result;
	}
}