parameters:
#    payment_meter.example.class: Payment\MeterBundle\Example

services:
#    payment_meter.example:
#        class: %payment_meter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
