reportMemberAssistance:
    pattern:  /reporte-de-infracciones
    defaults: { _controller: PaymentReportBundle:Report:reportMemberAssistance}

reportMember:
    pattern:  /generacion-de-listado-de-asistencia
    defaults: { _controller: PaymentReportBundle:Report:reportMember}    

reportExpensesAndCollections:
    pattern:  /reporte-de-gastos
    defaults: { _controller: PaymentReportBundle:Report:reportExpenses}                    