reportMemberAssistance:
    pattern:  /reportes/reporte-de-infracciones
    defaults: { _controller: PaymentReportBundle:Report:reportMemberAssistance}

reportMember:
    pattern:  /reportes/generacion-de-listado-de-asistencia
    defaults: { _controller: PaymentReportBundle:Report:reportMember}    

reportExpenses:
    pattern:  /reportes/reporte-de-gastos
    defaults: { _controller: PaymentReportBundle:Report:reportExpenses}   

reportCollection:
    pattern:  /reportes/reporte-de-cobros
    defaults: { _controller: PaymentReportBundle:Report:reportCollection}

reportDetailCollection:
    pattern:  /reportes/reporte-de-detalle-de-cobro/{id}
    defaults: { _controller: PaymentReportBundle:Report:reportDetailCollection}    
    
reportList:
    pattern:  /reportes/listado-de-reportes
    defaults: { _controller: PaymentReportBundle:Report:reportList}      

reportAccountState:
    pattern:  /reportes/estado-de-cuenta
    defaults: { _controller: PaymentReportBundle:Report:reportAccountState}      
_printAccountState:
    pattern:  /reportes/estado-de-cuenta/imprimir/{accountId}/{year}
    defaults: { _controller: PaymentReportBundle:Report:printAccountState }     
                                      