reportMemberAssistance:
    pattern:  /reporte-de-infracciones
    defaults: { _controller: PaymentReportBundle:Report:reportMemberAssistance}

reportMember:
    pattern:  /generacion-de-listado-de-asistencia
    defaults: { _controller: PaymentReportBundle:Report:reportMember}    

reportExpenses:
    pattern:  /reporte-de-gastos
    defaults: { _controller: PaymentReportBundle:Report:reportExpenses}   

reportCollection:
    pattern:  /reporte-de-cobros
    defaults: { _controller: PaymentReportBundle:Report:reportCollection}

reportDetailCollection:
    pattern:  /reporte-de-detalle-de-cobro/{id}
    defaults: { _controller: PaymentReportBundle:Report:reportDetailCollection}    
    
reportList:
    pattern:  /listado-de-reportes
    defaults: { _controller: PaymentReportBundle:Report:reportList}      

reportAccountState:
    pattern:  /estado-de-cuenta
    defaults: { _controller: PaymentReportBundle:Report:reportAccountState}                                            