security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_OPERATOR:       ROLE_USER
        ROLE_SECRETARY:       ROLE_USER
        ROLE_TREASURER:       ROLE_USER
        ROLE_ADMIN:       [ROLE_OPERATOR,ROLE_SECRETARY,ROLE_TREASURER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secured_area:
          pattern:  ^/
          anonymous:  ~
          form_login: 
            check_path: /login_check
            login_path: /login 
            default_target_path: /inicio
            always_use_default_target_path: true           
          logout:
            path: /logout
            target: /cerrar-sesion
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/gestion-de-gastos/, role: [ROLE_TREASURER, ROLE_SECRETARY] }
        - { path: ^/gestion-de-cobros/, role: ROLE_TREASURER }
        - { path: ^/gestion-de-consumo/, role: ROLE_OPERATOR }
        - { path: ^/gestion-de-miembros/, role: ROLE_SECRETARY }
        - { path: ^/gestion-de-medidores/, role: ROLE_SECRETARY }
        - { path: ^/gestion-de-pagos/, role: ROLE_SECRETARY }
        - { path: ^/gestion-de-miembros-directivas/, role: ROLE_ADMIN }
        - { path: ^/gestion-de-directivas/, role: ROLE_ADMIN }
        - { path: ^/gestion-de-tipo-pagos/, role: ROLE_ADMIN }
        - { path: ^/gestion-de-usuarios/, role: ROLE_ADMIN }
        - { path: ^/configurar-items, role: ROLE_ADMIN }
        - { path: ^/reportes/, role: ROLE_ADMIN }
    
        