_listManagerial:
    pattern:  /gestion-de-directivas/listado
    defaults: { _controller: PaymentManagerialBundle:Managerial:listManagerial}
_activeManagerial:
    pattern:  /gestion-de-directivas/activacion
    defaults: { _controller: PaymentManagerialBundle:Managerial:activeManagerial }
_editManagerial:
    pattern:  /gestion-de-directivas/edicion
    defaults: { _controller: PaymentManagerialBundle:Managerial:editManagerial }
_deleteManagerial:
    pattern:  /gestion-de-directivas/eliminacion
    defaults: { _controller: PaymentManagerialBundle:Managerial:deleteManagerial }
    
_listManagerialMember:
    pattern:  /gestion-de-miembros-directivas/listado
    defaults: { _controller: PaymentManagerialBundle:ManagerialMember:listManagerialMember }  
_activeManagerialMember:
    pattern:  /gestion-de-miembros-directivas/activacion
    defaults: { _controller: PaymentManagerialBundle:ManagerialMember:activeManagerialMember }
_editManagerialMember:
    pattern:  /gestion-de-miembros-directivas/edicion
    defaults: { _controller: PaymentManagerialBundle:ManagerialMember:editManagerialMember }   