parameters:
#    payment_data_access.example.class: Payment\DataAccessBundle\Example

services:
#    payment_data_access.example:
#        class: %payment_data_access.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
