parameters:
#    payment_member.example.class: Payment\MemberBundle\Example

services:
#    payment_member.example:
#        class: %payment_member.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
