Account:
    type: entity
    table: account
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        accountNumber:
            type: integer
            unsigned: false
            nullable: false
            column: account_number
        meterNumber:
            type: string
            length: 64
            fixed: false
            nullable: true
            column: meter_number
        memberId:
            type: integer
            unsigned: false
            nullable: false
            column: member_id
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
        isActive:
            type: boolean
            nullable: false
            column: is_active
    lifecycleCallbacks: {  }
