Fines:
    type: entity
    table: fines
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        finesTypeId:
            type: integer
            unsigned: false
            nullable: false
            column: fines_type_id
        cost:
            type: decimal
            nullable: false
        fineDate:
            type: datetime
            nullable: false
            column: fine_date
        memberId:
            type: integer
            unsigned: false
            nullable: false
            column: member_id
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
    lifecycleCallbacks: {  }
