Income:
    type: entity
    table: income
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        incomeTypeId:
            type: integer
            unsigned: false
            nullable: false
            column: income_type_id
        transactionId:
            type: integer
            unsigned: false
            nullable: false
            column: transaction_id
        consumptionId:
            type: integer
            unsigned: false
            nullable: true
            column: consumption_id
        finesId:
            type: integer
            unsigned: false
            nullable: true
            column: fines_id
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
    lifecycleCallbacks: {  }
