Transaction:
    type: entity
    table: transaction
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        transactionTypeId:
            type: integer
            unsigned: false
            nullable: false
            column: transaction_type_id
        managerialId:
            type: integer
            unsigned: false
            nullable: false
            column: managerial_id
        totalValue:
            type: decimal
            nullable: false
            column: total_value
        systemDate:
            type: datetime
            nullable: false
            column: system_date
        systemUserId:
            type: integer
            unsigned: false
            nullable: false
            column: system_user_id
    lifecycleCallbacks: {  }
