home:
    pattern:  /inicio
    defaults: { _controller: PaymentApplicationBundle:Default:welcome }

modal:
    pattern:  /modal
    defaults: { _controller: PaymentApplicationBundle:Default:modal }    