parameters:
#    payment_application.example.class: Payment\ApplicationBundle\Example

services:
#    payment_application.example:
#        class: %payment_application.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
