_listExpense:
    pattern:  /gestion-de-gastos/listado
    defaults: { _controller: PaymentTransactionBundle:Expense:listExpense }
_editExpense:
    pattern:  /gestion-de-gastos/edicion
    defaults: { _controller: PaymentTransactionBundle:Expense:editExpense }
_deleteExpense:
    pattern:  /gestion-de-gastos/eliminacion
    defaults: { _controller: PaymentTransactionBundle:Expense:deleteExpense }
    
_itemsCollection:
    pattern:  /gestion-de-cobros/cobro-mensualidades
    defaults: { _controller: PaymentTransactionBundle:Collection:itemsCollection }  
_printCollection:
    pattern:  /gestion-de-cobros/imprimir/{accountId}
    defaults: { _controller: PaymentTransactionBundle:Collection:printCollection } 
_listReverse:
    pattern:  /reversa-de-cobros/reversa-listado
    defaults: { _controller: PaymentTransactionBundle:Reverse:reverse }
_reverseCollection:
    pattern:  /reversa-de-cobros/reversar
    defaults: { _controller: PaymentTransactionBundle:Reverse:reverseExec } 