parameters:
#    payment_transaction.example.class: Payment\TransactionBundle\Example

services:
#    payment_transaction.example:
#        class: %payment_transaction.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
