_listFinesType:
    pattern:  /gestion-de-tipo-multas/listado
    defaults: { _controller: PaymentFinesBundle:FinesType:listFinesType }
_activeFinesType:
    pattern:  /gestion-de-tipo-multas/activacion
    defaults: { _controller: PaymentFinesBundle:FinesType:activeFinesType }
_editFinesType:
    pattern:  /gestion-de-tipo-multas/edicion
    defaults: { _controller: PaymentFinesBundle:FinesType:editFinesType }
_deleteFinesType:
    pattern:  /gestion-de-tipo-multas/eliminacion
    defaults: { _controller: PaymentFinesBundle:FinesType:deleteFinesType }
