parameters:
#    payment_fines.example.class: Payment\FinesBundle\Example

services:
#    payment_fines.example:
#        class: %payment_fines.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
